### ISSUE TITLE
CRC error triggers python exception

### ISSUE THREAD

**Issue by NigelCoxon** [NigelCoxon/Hass-heatmiser#1]
Occasional CRC errors cause an exception

...
2020-12-28 07:52:20 ERROR (SyncWorker_10) [custom_components.heatmiser_ndc.heatmiser] Bad CRC
2020-12-28 07:52:20 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.bathroom fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/heatmiser_ndc/climate.py", line 202, in update
    self.dcb = self.therm.read_dcb()
  File "/config/custom_components/heatmiser_ndc/heatmiser.py", line 325, in read_dcb
    self.dcb = self._hm_read_address()
  File "/config/custom_components/heatmiser_ndc/heatmiser.py", line 296, in _hm_read_address
    response = self._hm_send_address(self.address, 0, 0, 0)
  File "/config/custom_components/heatmiser_ndc/heatmiser.py", line 287, in _hm_send_address
    verification = self._hm_verify_message_crc_uk(
  File "/config/custom_components/heatmiser_ndc/heatmiser.py", line 163, in _hm_verify_message_crc_uk
    dest_addr = datal[0]
IndexError: list index out of range
...

After an error, the verify routine in heatmiser.py continues to check other parameters. I think it should exit once its found an error. 

Also output to console should be removed - use logging instead

**Comment by NigelCoxon** [comment]
Code updated, various improvements made
